---
# building configurator micro-service using dotnet cli

platform: linux

image_resource:
  type: docker-image
  source:
    repository: microsoft/aspnetcore-build
    tag: "2.0"

inputs:
  - name: codebase

outputs:
  - name: configurator

run:
  path: dotnet
  args: 
    - publish
    - codebase/Matrix.Agent.Configurator
    - --framework
    - netcoreapp2.0
    - --configuration
    - Release
    - --output
    - ../../configurator

...