---
# concourse-ci build pipeline for building matrix agent micro-services

resources:
  - name: codebase
    type: git
    source:
      uri: ((git-repo))/matrix.net.git
      username: ((git-username))
      private_key: |-
        ((git-password))
      branch: master

  - name: version
    type: semver
    source:
      driver: git
      username: ((git-username))
      private_key: |
        ((git-password))
      uri: ((git-repo))/concourse.git
      branch: master
      file: matrix.net
      initial_version: 1.0.0
      commit_message: "build: bumping %file% to %version%"

  - name: registry
    type: docker-image
    source:
      repository: ((docker-repo))/matrix.registry
      username: ((docker-username))
      password: ((docker-password))

  - name: configurator
    type: docker-image
    source:
      repository: ((docker-repo))/matrix.configurator
      username: ((docker-username))
      password: ((docker-password))

  - name: directory
    type: docker-image
    source:
      repository: ((docker-repo))/matrix.directory
      username: ((docker-username))
      password: ((docker-password))

  - name: journal
    type: docker-image
    source:
      repository: ((docker-repo))/matrix.journal
      username: ((docker-username))
      password: ((docker-password))

  - name: postman
    type: docker-image
    source:
      repository: ((docker-repo))/matrix.postman
      username: ((docker-username))
      password: ((docker-password))

  - name: web
    type: docker-image
    source:
      repository: ((docker-repo))/matrix.web
      username: ((docker-username))
      password: ((docker-password))

jobs:
  - name: build
    plan:
        # git clone or pull version repository
      - get: version

        # git clone or pull codebase repository
      - get: codebase
        # trigger build job for any commits to codebase repository
        trigger: true
        
        # compile registry
      - task: build-registry
        file: codebase/Matrix.Build/registry.yml

        # build and push registry image to docker repository
      - put: registry
        params:
          build: registry
          build_args:
            source: .
          tag_as_latest: true

        # build configurator image
      - task: build-configurator
        file: codebase/Matrix.Build/configurator.yml

        # push configurator image to docker repository
      - put: configurator
        params:
          build: configurator
          build_args:
            source: .
          tag_as_latest: true

        # build directory image
      - task: build-directory
        file: codebase/Matrix.Build/directory.yml

        # push directory image to docker repository
      - put: directory
        params:
          build: directory
          build_args:
            source: .
          tag_as_latest: true

        # build journal image
      - task: build-journal
        file: codebase/Matrix.Build/journal.yml
        
        # push journal image to docker repository
      - put: journal
        params:
          build: journal
          build_args:
            source: .
          tag_as_latest: true

        # build postman image
      - task: build-postman
        file: codebase/Matrix.Build/postman.yml

        # push postman image to docker repository
      - put: postman
        params:
          build: postman
          build_args:
            source: .
          tag_as_latest: true

        # build web image
      - task: build-web
        file: codebase/Matrix.Build/web.yml

        # push web image to docker repository
      - put: web
        params:
          build: web
          build_args:
            source: .
          tag_as_latest: true

        # bumping patch version to 1.0.x and push to git repository
      - put: version
        params:
          bump: patch
...